### ISSUE TITLE
Ubuntu 14.04 wants a newer version of libstdc++6

### ISSUE THREAD

**Issue by davidpuzey** [tiliado/webkitgtk-pkg-deb#1]
When I try getting the latest libwebkit2gtk from https://launchpad.net/~nuvola-player-builders/+archive/ubuntu/webkit on Ubuntu 14.04 it won't upgrade.
I tried removing it (and a few of the dependencies), when I tried reinstalling I got this:
libwebkit2gtk-4.0-37 : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
A little digging online and it looks like libstdc++6 isn't >= 4.9 on 14.04.

Am I missing something?
I could use another ppa (ppa:ubuntu-toolchain-r/test seems to be popular) to pull in a later version, but it would be nice if it all came from the same place.

**Comment by fenryxo** [comment]
Hello @davidpuzey. Thanks for taking the time to report this issue. I've just uploaded the gcc-4.9_4.9.3-8ubuntu2~14.04~tiliado1 package to the build queue of the WebKit for Nuvola Player PPA.

**Comment by fenryxo** [comment]
Ok, it wasn't it. The second attempt with gcc-6_6.1.1-3ubuntu11~14.04.1~tiliado1.

**Comment by fenryxo** [comment]
Dependency issue fixed. Thanks for your bug report.
